[package]
name = "screenshotocr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arboard = "3.3.0"
gtk = {package = "gtk", version = "0.18.1", features = ["v3_24"]}
rusty-tesseract = "1.1.9"
